### PR TITLE
#1416: Improve German translations

### LINKED ISSUE #1416: Improve German translations
**Describe the bug**
The German translation is a little clunky and wrong at some points.

**To Reproduce**
Turn on German translation as a native speaker.

**Expected behavior**
Proper German 🙃 

I'll provide a PR in a second.

Best regards  
Ronny

### PR DESCRIPTION
**Pull request by GitRon**
closes #1416.

### CODE REVIEW

File: l10n/de_DE.ts [hunk 1]
```diff
@@ -1,22 +1,22 @@
 export default {
   search: {
-    placeholder: 'Geben Sie ein Schlüsselwort ein...',
```
Comment (GitRon) [inline l10n/de_DE.ts:3]: this is technically correct but sounds very clunky...

File: l10n/de_DE.ts [hunk 2]
```diff
@@ -1,22 +1,22 @@
...
+    placeholder: 'Suchbegriff eingeben...',
   },
   sort: {
     sortAsc: 'Spalte aufsteigend sortieren',
     sortDesc: 'Spalte absteigend sortieren',
   },
   pagination: {
-    previous: 'Bisherige',
+    previous: 'Vorherige',
```
Comment (GitRon) [inline l10n/de_DE.ts:10]: Not 100% percise

File: l10n/de_DE.ts [hunk 3]
```diff
@@ -1,22 +1,22 @@
...
     next: 'Nächste',
     navigate: (page, pages) => `Seite ${page} von ${pages}`,
     page: (page) => `Seite ${page}`,
-    showing: 'Anzeigen',
+    showing: 'Datensätze',
```
Comment (GitRon) [inline l10n/de_DE.ts:14]: You can't use the "showing x of y" in German, so I had to get a little creative. In the perfect world, the whole "sentence" would be a translatable.

File: l10n/de_DE.ts [hunk 4]
```diff
@@ -1,22 +1,22 @@
...
     of: 'von',
-    to: 'zu',
-    results: 'Ergebnisse',
+    to: 'bis',
+    results: 'Ergebnissen',
```
Comment (GitRon) [inline l10n/de_DE.ts:17]: Wrong case

File: l10n/de_DE.ts [hunk 5]
```diff
@@ -1,22 +1,22 @@
...
   },
   loading: 'Wird geladen...',
-  noRecordsFound: 'Keine übereinstimmenden Aufzeichnungen gefunden',
+  noRecordsFound: 'Keine passenden Daten gefunden',
```
Comment (GitRon) [inline l10n/de_DE.ts:20]: less clunky 🙂

**Comment by GitRon** [comment]
Could anybody please have a look at the changes? Should be a quick one, right? I'm going to use it in production soon and the current translations are a little off 😅
